apiVersion: monitoring.kubecontroller.com/v1alpha1
kind: LogWatcher
metadata:
  name: load-based-scaling
  namespace: default
spec:
  podNamespace: webapp
  podLabelSelector:
    app: webapp
  matchPattern: "request.*processed|error.*rate.*high|load.*increased"
  actions:
    restartPod: false  # Don't restart for load-based scaling
  scaling:
    minReplicas: 2
    maxReplicas: 20
    scaleUpThreshold: 10
    scaleDownThreshold: 2
    deploymentName: webapp-deployment
  alerting:
    slack:
      webhookURL: "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK"
      channel: "#scaling-alerts"
      username: "LogWatcher"
    webhook:
      url: "https://api.company.com/scaling-webhook"
      method: "POST"
      headers:
        Content-Type: "application/json"
  metrics:
    enabled: true
    port: 8080
    path: "/metrics"
  reconcileInterval: 30
  tailLines: 150 